### ISSUE TITLE
Error compiling instrumentation handlers

### ISSUE THREAD

**Issue by beckdav** [NVlabs/SASSI#14]
Hi, 
I am trying to install and use SASSI, however I am having a problem compiling the instrumentation handlers, Section 6 user guide. I have Ubuntu 12.04, Python 2.7.3 and am compiling for -gencode arch=compute_50,code=sm_50 and have the following environment variable set in env.mk

Any hints as to where I might be going wrong are greatly appreciated, Many Thanks.

env.mk:
`export CUDA_HOME=/usr/local/cuda-7.0
export SASSI_HOME=/usr/local/sassi7
export SASSI_SRC=/home/ssc-obdh/Documents/SASSI-master
export INST_LIB_DIR=$SASSI_SRC/instlibs/lib
export CCBIN=/usr/bin/`

`ssc-obdh@ssc-obdh-OptiPlex-790:~/Documents/SASSI-master/instlibs$ make
make -C src install
make[1]: Entering directory '/home/ssc-obdh/Documents/SASSI-master/instlibs/src'
/usr/local/cuda-7.0/bin/nvcc -ccbin /usr/bin/ -std=c++11 \
--compiler-options -Wall -O3 -gencode arch=compute_50,code=sm_50             
	        -lineinfo -c -rdc=true -o branch.o branch.cu   \
		--maxrregcount=16          \
		--compiler-options -Wall   \
		-I/usr/local/sassi7/include    \
		-I/usr/include/boost/include    \
		-I/usr/local/cuda-7.0/extras/CUPTI/include/        \
		-I/home/ssc-obdh/Documents/SASSI-master/instlibs/utils/    \
		-I/home/ssc-obdh/Documents/SASSI-master/instlibs/include
/home/ssc-obdh/Documents/SASSI-master/instlibs/utils/sassi_srcmap.hpp(272): error: too few arguments for class template "std::set"
...

/usr/include/boost/smart_ptr/shared_ptr.hpp(305): error: function "boost::shared_ptr<T>::shared_ptr(const boost::shared_ptr<boost::re_detail::named_subexpressions> &) [with T=boost::re_detail::named_subexpressions]" (declared implicitly) cannot be referenced -- it is a deleted function
          detected during:
            instantiation of "boost::shared_ptr<T> &boost::shared_ptr<T>::operator=(const boost::shared_ptr<T> &) [with T=boost::re_detail::named_subexpressions]" 

...
6 errors detected in the compilation of "/tmp/tmpxft_00002f63_00000000-7_branch.cpp1.ii".
make[1]: *** [branch.o] Error 2
make[1]: Leaving directory '/home/ssc-obdh/Documents/SASSI-master/instlibs/src'
make: *** [instlibs] Error `

**Comment by mwstephenson** [comment]
Hi There,

Have you had any luck figuring it out?

What version of GCC are you using?  I believe the highest version I tried
was 4.8.3 because there were some compatibility issues between GCC and the
CUDA 7 nvcc.  I'm wondering if that might have something to do with those
errors.

Thanks a lot,
Mark

**Comment by beckdav** [comment]
Hi Mark, 
Thanks for the reply, however no luck as yet ... 
I am using version 4.8.1 of GCC, and have version 1.46.1 of boost, 
as all errors appear to relate the boost library do you know what version of boost you used? 

Many Thanks, 
Becky.

**Comment by beckdav** [comment]
Hi Mark, 
I just updated my boost version to 1.55 and can confirm that this fixed the above error. 
Looking forward to getting started using SASSI ! 
Many Thanks,
Becky.

**Comment by mwstephenson** [comment]
Hi Becky,

Excellent, glad to hear it!  Thanks for the info.

Best wishes,
Mark
