### ISSUE TITLE
Plans for Pascal and later architecture support?

### ISSUE THREAD

**Issue by hjunkim** [NVlabs/SASSI#15]
Hi Mark,

Do you have any plan to extend the SASSI to support Pascal or later architectures (ex. Volta)?

Thanks.
Hyunjun

**Comment by mwstephenson** [comment]
Hi Hyunjun,

No, sorry we do not have plans to support anything beyond Maxwell.  There
is some hope that we will have something better than SASSI to release in
the future, but don't hold your breath.

Thanks,
Mark
