### ISSUE TITLE
Problem in running the example

### ISSUE THREAD

**Issue by kakulo** [NVlabs/SASSI#18]
Hi,

I get an error when running the example in SASSI_SRC/example.

here is the bug:

surface86@guo7:make
/g/g90/guo7/guo-libs/sassi7//bin/nvcc -c -o matrixMul.o matrixMul.cu -gencode arch=compute_35,code=sm_35 -Xptxas --sassi-inst-before="memory" -Xptxas --sassi-before-args="mem-info" -g -O3 -dc  -I./inc 
sh: /g/g90/guo7/guo-libs/sassi7//bin/ptxas: cannot execute binary file
make: *** [matrixMul.o] Error 126

Thanks!

**Comment by sivahari** [comment]
This appears to be a file permission issue. Ensure that user guo7 can execute /g/g90/guo7/guo-libs/sassi7/bin/ptxas. You can try `chmod +x /g/g90/guo7/guo-libs/sassi7/bin/ptxas`. I hope this helps.

Siva

**Comment by kakulo** [comment]
Hi Dr. Hari,

I have permission to the ptxas file. You see,

surface86@guo7:ls -al
total 44988
drwxr-xr-x  3 guo7 guo7    4096 Apr 15  2015 .
drwxr-xr-x 15 guo7 guo7    4096 Apr 15  2015 ..
-rwxr-xr-x  1 guo7 guo7  129176 Mar 20  2015 bin2c
-rwxr-xr-x  1 guo7 guo7     215 Mar 20  2015 computeprof
drwxr-xr-x  2 guo7 guo7    4096 Apr 15  2015 crt
-rwxr-xr-x  1 guo7 guo7 8434332 Mar 20  2015 cuda-gdb
-rwxr-xr-x  1 guo7 guo7  452543 Mar 20  2015 cuda-gdbserver
-rwxr-xr-x  1 guo7 guo7     781 Mar 20  2015 cuda-install-samples-7.0.sh
-rwxr-xr-x  1 guo7 guo7  356192 Mar 20  2015 cuda-memcheck
-rwxr-xr-x  1 guo7 guo7 3727744 Mar 20  2015 cudafe
-rwxr-xr-x  1 guo7 guo7 3390552 Mar 20  2015 cudafe++
-rwxr-xr-x  1 guo7 guo7  217200 Mar 20  2015 cuobjdump
-rwxr-xr-x  1 guo7 guo7  186320 Mar 20  2015 fatbinary
-rwxr-xr-x  1 guo7 guo7  125080 Mar 20  2015 filehash
-rwxr-xr-x  1 guo7 guo7     219 Mar 20  2015 nsight
-rwxr-xr-x  1 guo7 guo7  229840 Mar 20  2015 nvcc
-rw-r--r--  1 guo7 guo7     411 Mar 20  2015 nvcc.profile
-rwxr-xr-x  1 guo7 guo7 8399408 Mar 20  2015 nvdisasm
-rwxr-xr-x  1 guo7 guo7 6070624 Mar 20  2015 nvlink
-rwxr-xr-x  1 guo7 guo7 6437944 Mar 20  2015 nvprof
-rwxr-xr-x  1 guo7 guo7  150328 Mar 20  2015 nvprune
-rwxr-xr-x  1 guo7 guo7     215 Mar 20  2015 nvvp
-rwxrwxr-x  1 guo7 guo7 7446552 Jun 17 13:33 ptxas
surface86@guo7:./nvcc
nvcc fatal   : No input files specified; use option --help for more information

Thanks.

**Comment by mwstephenson** [comment]
Hi,

Are you able to directly invoke ptxas?  Can you try "ptxas -h", for
instance?

It's very possible that you have the wrong binary for your system, and thus
it won't execute.  What OS/Arch are you running with?

Thanks,
Mark

**Comment by kakulo** [comment]
Hi Mark,

Thanks! 
I cannot directly invoke ptxas from sassi7/bin. Here is what I get. 

surface86@guo7:/g/g90/guo7/guo-libs/sassi7/bin/ptxas -h
-bash: /g/g90/guo7/guo-libs/sassi7/bin/ptxas: cannot execute binary file
surface86@guo7:uname -a
Linux surface86 2.6.32-696.23.1.1chaos.ch5.6.x86_64 #1 SMP Mon Mar 19 17:25:21 PDT 2018 x86_64 x86_64 x86_64 GNU/Linux
surface86@guo7:lsb_release -a
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch:graphics-4.0-amd64:graphics-4.0-noarch:printing-4.0-amd64:printing-4.0-noarch
Distributor ID:	RedHatEnterpriseServer
Description:	Red Hat Enterprise Linux Server release 6.9 (Santiago)
Release:	6.9
Codename:	Santiago

Regards,
Luanzheng Guo

**Comment by mwstephenson** [comment]
Hi  Luanzheng,

I have never tested it with Red Hat.  Did you use the centos6.7
installation?  I'm not sure if the CentOS 6.7 binaries would be compatible
with RedHat 6.9.

Thanks,
Mark

**Comment by kakulo** [comment]
Hi Mark,

No, I didn't use the centos installation. And my CPU is Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
. Does it affect? 

Thanks,
Luanzheng Guo

**Comment by mwstephenson** [comment]
Try it with this installer:

https://github.com/NVlabs/SASSI/releases/download/v1.0.5/SASSI_x86_64_centos6.7.run

I think that's your best bet.

**Comment by kakulo** [comment]
Thanks, I am trying.

**Comment by kakulo** [comment]
Hi Mark,

Thanks. SASSI_x86_64_centos6.7.run works. 
surface86@guo7:/g/g90/guo7/guo-libs/sassi7/bin/ptxas -h
Usage  : ptxas [options] <ptx file>,...
Options
=======

--abi-compile <yes|no>                                                (-abi)    
        Enable/Disable the compiling of functions using ABI.
        Default value:  'yes'.

--allow-expensive-optimizations <true|false>                          (-allow-expensive-optimizations)
        Enable (disable) to allow compiler to perform expensive optimizations   
        using maximum available resources (memory and compile-time).
        If unspecified default behavior is to enable this feature for optimization
        level >= O2.

--compile-only                                                        (-c)      
        Generate relocatable object.

--def-load-cache                                                      (-dlcm)   
        Default cache modifier on global/generic load.
        Default value:  'ca'.

--def-store-cache                                                     (-dscm)   
        Default cache modifier on global/generic store.

I am getting the following bug this time.

surface86@guo7:make
/g/g90/guo7/guo-libs/sassi7//bin/nvcc -o matrixMul matrixMul.o -gencode arch=compute_35,code=sm_35 -L../instlibs/lib -lmemdiverge -L/g/g90/guo7/guo-libs/sassi7//extras/CUPTI/lib64 -lcupti  -lcudadevrt -Xlinker -rpath,/g/g90/guo7/guo-libs/sassi7//extras/CUPTI/lib64 
nvlink warning : SM Arch ('sm_35') not found in '../instlibs/lib/libmemdiverge.a:memdiverge.o'
nvlink error   : Undefined reference to '_Z20sassi_before_handlerP17SASSIBeforeParamsP17SASSIMemoryParams' in 'matrixMul.o'
make: *** [matrixMul] Error 255

Thanks!

**Comment by kakulo** [comment]
Hi Mark,

The problem is solved. 
Thanks! The issue is thereby closed.

Luanzheng Guo
