### ISSUE TITLE
Error in running example:CUPTI_ERROR_NOT_INITIALIZED

### ISSUE THREAD

**Issue by Sophia522** [NVlabs/SASSI#19]
when I run the example ,the following error occurred. I have no solution to it.
example# ./matrixMul
/SASSI/instlibs/utils/sassi_lazyallocator.hpp:86:Error CUPTI_ERROR_NOT_INITIALIZED for CUPTI API function 'cuptiSubscribe'.

Thanks.

**Comment by yuehs1994** [comment]
I met the same problem，even though I reinstalled sassi.
