### ISSUE TITLE
Error: driver shutting down, when using "ophist"

### ISSUE THREAD

**Issue by leimingyu** [NVlabs/SASSI#4]
I am running SASSI on rodinia benchmarks. When I compiled the program using ophist option and run the executable,  it sometimes shows "Error: driver shutting down".

I checked the output, sassi-ophist.txt, is there, but don't know what caused the error msg.

Any suggestions? Thanks in advance.

-Leiming

**Comment by mwstephenson** [comment]
Hi Leiming,

Does this happen for all the Rodinia applications?  Is there one you could point me at?  Also, what card and driver are you using?

Thanks a lot,
Mark

**Comment by leimingyu** [comment]
Hello Mark,
I tested on a subset of Rodinia 3.0, including backprop, bfs, b+tree, cfd, dwt2d, gaussian, heartwall, hotspot, hybridsort, kmeans. They all showed "Error: driver shutting down".
I am using ubuntu 14.04 x64 with K40c and cuda 7.0.

**Comment by mwstephenson** [comment]
Hi Leiming,  I think this issue is now fixed.  I was calling cudaDeviceSynchronize in a static object destructor, which was run after/during CUDA driver shutdown.

Thanks,
Mark
