### ISSUE TITLE
ptxas -h does not show sassi options

### ISSUE THREAD

**Issue by trinayan** [NVlabs/SASSI#7]
I tried installing sassi . I have a kepler machine with cuda 7.0. The installation script shows success but after I do ptxas -h I find no sassi option. Is the installation script faulty?

**Comment by mwstephenson** [comment]
It's possible that the installation script is faulty.  The installation
script simply copies your existing CUDA 7 installation to a new directory,
then copies over the SASSI header files and adds the SASSI-enable ptxas to
the new directory's 'bin' directory.

Did you verify that a new directory was created?  If so, are you using the
ptxas in that new directory's bin directory?

Thanks a lot,
Mark

**Comment by trinayan** [comment]
Hey. Yes I got it working. I was running in the wrong directory. Thanks a lot. Anyways what is the reason SASSI does not support instrumentation on texture memory or constant memory operations?. Is it a developmental issue or it can never be done?. Thanks again

**Comment by mwstephenson** [comment]
Great!  Good questions.  To clarify, SASSI can instrument all instructions,
but it does not treat texture operations or constant loads as memory
operations.  That is, if you ask SASSI to instrument (only) memory
operations, texture operations that operate on memory and constant loads
will not be instrumented.

You can certainly still instrument texture operations and get the values in
all of the pertinent registers, but you'll have to interpret that data on
your own.  This likely will never change, as texture operations can have
some really involved semantics.  It's not clear to me in the general case
what the "address" of a texture operation should be.

On the other hand, it would not be difficult to treat constant loads as
memory operations.  Constant memory is a truly unique space, however, so
I'm not sure it should be treated the same way that the shared, local, and
global spaces are.  You can still use SASSI to identify constant loads by
instrumenting all instructions and ignoring opcodes other than
SASSI_OP_LDC.  I'll have to think about this more for future releases of
SASSI.  Would you like constant memory to be lumped in with the other
spaces?

Thanks,
Mark

**Comment by trinayan** [comment]
Ok. Thank you very much Mr.Stephenson. I have started to work with SASSI  at our research lab at Northeastern at the moment and I think it is a great tool.

**Comment by trinayan** [comment]
So I was trying to observe the number of unique cachelines touched over time . With a CPU tool like Pin that is really easy because you can print to the file your address or whatever you want to after each instruction. However in SASSI you can only dump the stats at the end of execution which is a problem because one may not know how many instructions they will encounter at runtime and thus cannot allocate a fixed size array to collect this information. Even if it was possible the size of the array might be too large if the program's runtime is long. Is there any way by which I can use SASSI to print to a file say after every instruction is executed or is it not possible at all?.

**Comment by mwstephenson** [comment]
Hi!  This is one of the more frustrating things about GPU instrumentation.
It is unfortunate that things that are very simple on a CPU are currently
quite painful on GPUs.  In particular, I have found the lack of common data
structures frustrating, and as you mention, it would be great if we could
write to a file from device code.  The good news is that things are
progressively getting better as CUDA matures.  Internally we have developed
a library that merely pins down host memory to serve as a queue that we can
push data out to.  A host-side thread pops data off the queue.  I'm trying
to get permission to release it as a utility, but I don't have a good ETA
to provide you.  So, it might be worth your time to roll your own utility
that does the same thing.  I'll get back to you if/when we release it.

Thanks a lot,
Mark

**Comment by trinayan** [comment]
Ok Thank you. I found that the Program counters generated in the branch divergence tool are not found in the cuobjdump sass of the output. Is there any reason I cannot see them?. It would be very helpful to see those particular instructions directly.

**Comment by mwstephenson** [comment]
Hi there!  There is now a utility and an example that shows you how to map a SASSI program counter (a PUPC) to a CUDA source line.  Please look at the branch example, and see how to compile your application by looking at the `branch` target in the `Makefile` in the `example` directory.  Sorry this took so long!
