### ISSUE TITLE
Handlers for Error Injection

### ISSUE THREAD

**Issue by pfritzgerald** [NVlabs/SASSI#8]
Hi,

In one of the case studies in the paper, SASSI was used to perform error injection to study application vulnerability. I am wondering if the handlers that were written for such study are available. Or is there a plan to make them available?

Thank you

**Comment by mwstephenson** [comment]
Siva Hari has done the resilience work. I believe that you and Siva communicated privately about this, correct?

**Comment by pfritzgerald** [comment]
Yes we did communicate.

Thank you

On Thu, May 26, 2016 at 1:53 PM, Mark Stephenson notifications@github.com
wrote:

> Siva Hari has done the resilience work. I believe that you and Siva
> communicated privately about this, correct?
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/NVlabs/SASSI/issues/8#issuecomment-221945271

##
